### ISSUE TITLE
Couldn't find property 'processResources' using gradle:0.14.4

### ISSUE THREAD

**Issue by victor4collabora** [hamsterksu/android-aptlibs-gradle-plugin#2]
When I try to Make a project gradle fails on compileDebugJava task:

Error:Execution failed for task ':app:compileDebugJava'.

> Could not find property 'processResources' on com.android.build.gradle.internal.api.ApplicationVariantImpl_Decorated@4f280f39.

**Comment by hamsterksu** [comment]
fixed in https://github.com/hamsterksu/android-aptlibs-gradle-plugin/commit/bff14800c2f096d85a2aea6d5ade7e9aa71be42d 
lets use v1.2.1
